name = "juliahub-test-registry"
uuid = "78cb13ad-96fd-4bc6-b774-a8c1b86a0eb7"
repo = ""

description = """
juliahub-test-registry
"""

[packages]
c91e804a-d5a3-530f-b6f0-dfbca275c004 = { name = "Gadfly", path = "G/Gadfly" }
